name: Deploy to GitHub Pages (Simple)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js app
        run: npm run build
        
      - name: Debug - Check build output
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Checking for build outputs:"
          ls -la out/ 2>/dev/null || echo "No out directory found"
          ls -la .next/ 2>/dev/null || echo "No .next directory found"
          ls -la dist/ 2>/dev/null || echo "No dist directory found"
          
      - name: Prepare deployment files
        run: |
          if [ -d "out" ]; then
            echo "Using out directory"
            DEPLOY_DIR="out"
          elif [ -d ".next" ]; then
            echo "Using .next directory - creating out from .next"
            mkdir -p out
            cp -r .next/static out/_next/static 2>/dev/null || true
            cp -r .next/server/pages out/ 2>/dev/null || true
            DEPLOY_DIR="out"
          else
            echo "No build output found, creating minimal deployment"
            mkdir -p out
            echo '<html><body><h1>Build Error</h1><p>No build output found</p></body></html>' > out/index.html
            DEPLOY_DIR="out"
          fi
          echo "DEPLOY_DIR=$DEPLOY_DIR" >> $GITHUB_ENV
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
        
      - name: Add .nojekyll to out
        run: touch out/.nojekyll

          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
