name: Deploy to GitHub Pages (Working)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build and Export
        run: |
          npm run build
          npx next export || echo "Export command failed, trying alternative approach"
          
      - name: Check build output
        run: |
          if [ -d "out" ]; then
            echo "✅ out directory found"
            ls -la out/
          elif [ -d ".next" ]; then
            echo "❌ out directory not found, but .next exists"
            echo "Creating out directory from .next..."
            mkdir -p out
            cp -r .next/static out/_next/static 2>/dev/null || true
            echo '<html><body><h1>OAC Website</h1><p>Build completed but static export may have issues</p></body></html>' > out/index.html
          else
            echo "❌ No build output found"
            mkdir -p out
            echo '<html><body><h1>Build Failed</h1><p>No build output generated</p></body></html>' > out/index.html
          fi
          
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
