name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js app
        run: npm run build
        
      - name: Debug - List files after build
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of .next directory (if exists):"
          ls -la .next/ || echo ".next directory not found"
          echo "Contents of out directory (if exists):"
          ls -la out/ || echo "out directory not found"
          
      - name: Create out directory if it doesn't exist
        run: |
          if [ ! -d "out" ]; then
            echo "out directory not found, creating it..."
            mkdir -p out
            echo "Copying .next/static to out/_next/static..."
            cp -r .next/static out/_next/static 2>/dev/null || echo "No static files to copy"
            echo "Creating basic index.html..."
            echo '<html><body><h1>Build Error</h1><p>Static export failed</p></body></html>' > out/index.html
          fi
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
