# Deploy Hugo site to Firebase Hosting
# https://github.com/firebase/firebase-tools

name: Deploy Hugo site to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Hugo (latest extended version)
        run: |
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep tag_name | cut -d '"' -f4)
          wget https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/hugo_extended_${HUGO_VERSION#v}_Linux-64bit.tar.gz
          tar -xzf hugo_extended_${HUGO_VERSION#v}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ONLINE_ASTRONOMY_COMPETITION }}
          channelId: live
          projectId: online-astronomy-competition
